### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by BWibo**
Enable OpenShift support
 - [x] #32 
 - [x] #33

### CODE REVIEW

**Comment by BWibo** [comment]
@gislab-augsburg, @klml: I just released `3.0.0-beta1`.
Please go through the [CHANGELOG](https://github.com/tum-gis/sddi-ckan-k8s/blob/release/3.0.0/CHANGELOG.md) and test the new version. When everything is fine, we can release `3.0.0`.

**Note:** I incuded some dependency updates. Please make sure to go through the changelog before testing this in an existing setup. The Solr upgrade should not require any additional action or cause problem, but make sure to make backups and read the docs first.

**Comment by gislab-augsburg** [comment]
@BWibo :
I tested release `sddi-ckan-3.0.0-beta1`. Whith disabling the solr init container in our values with
```
solr:	
  initContainers: []
```
it works perfectly. No problems with the new Solr version or the other the upgrades.

So from our side, you can can release `3.0.0`   🚀

**Comment by BWibo** [comment]
Just post the anonymized `values.yml` here. I'll document it and add the example.

**Comment by gislab-augsburg** [comment]
@BWibo :
Yes, I applied the new version to an instance with content. I ran `ckan search-index rebuild` and the new Solr version worked without issues. Actually, I first tried the default Solr version:
https://github.com/tum-gis/sddi-ckan-k8s/blob/dcf71fa42bd080d021725964450f175a165ff582/charts/sddi-ckan/charts/solr/values.yaml#L12-L18
Then changed to `tag: 2.9-solr9-spatial` because we had `tag: 2.9-solr8-spatial` before. Both working without issues.

I will provide the example values for OpenShift the next days.

**Comment by BWibo** [comment]
@gislab-augsburg Hey, I wanted to ask about the example file. I would like to include this in the release, so I can point users to the example for OpenShift usage, for which we add support in this release. Thx in advance.

**Comment by gislab-augsburg** [comment]
Hey @BWibo, 
Sorry for delay. Please see attached draft for minimal example values for openShift: [openshift.zip](https://github.com/tum-gis/sddi-ckan-k8s/files/14570170/openshift.zip)

Some comments on it:

- I did not include the extra volumes, volume mounts and CMs for local licenses, local .ini and custom ckan-schema because this is not OpenShift but LHM specific. If you are interested, I can provide an example of these, too.
- We use route instead of ingress at the moment, so I included our local route template which we use with an extra chart and the value `ckan.host`. 
- We do not use datapusher, but replace it with ckanext-xloader which is installed in our docker image [sddi-urban](https://github.com/tum-gis/ckan-docker/pull/54).
Datapusher raised an OpenShift related error and the pod failed when we included it at the beginning. We did not resolve the error but decided to just disable datapusher and use xloader.

Error in datapusher pod:
```
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Sep 29 13:42:09 2023] ***
compiled with version: 10.2.1 20201203 on 01 March 2023 09:19:15
os: Linux-4.18.0-372.64.1.el8_6.x86_64 #1 SMP Thu Jun 29 14:42:09 EDT 2023
nodename: datapusher-5b9c686959-k9s87
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /srv/app
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
cannot setgid() as non-root user
```
- We do not use certIssuer. Didn't try that at all.

**Pull request merged**
