### PR TITLE
Enable clamav for scanning files

### PR DESCRIPTION
**Pull request by ilchebedelovski**

### CODE REVIEW

**Comment by BWibo** [comment]
@MarijaKnezevic please don't just merge things to `main`. We want a clean release management and I would like to review stuff before it is released here. Please keep the develop in a branch until it is complete and

I reset `main` to where it was before.

**Comment by MarijaKnezevic** [comment]
@BWibo OK. I merged it because we are planning the next pentest during the next week. This feature of Ilche is tested.

**Comment by BWibo** [comment]
@MarijaKnezevic I suggest we create a beta release for that.

**Comment by MarijaKnezevic** [comment]
yes, fine for me. I will coordinate this with Ilche to create beta release from branch and then when everything is fine to confirm and request merging to main

**Comment by gislab-augsburg** [comment]
One question: Did I get it right that ckanext-clamav like included in the sddi-base image [here](https://github.com/tum-gis/ckan-docker/commit/0fce9defdfe985a01561b5fe3f375125352f2df9) needs clamav as a service, which is included in [sddi-ckan-3.1.0-beta1](https://github.com/tum-gis/sddi-ckan-k8s/tree/sddi-ckan-3.1.0-beta1), but not yet in the main branch?

**Comment by MarijaKnezevic** [comment]
@gislab-augsburg yes, that is true.
It is not yet merged to the [sddi-ckan-k8s](https://github.com/tum-gis/sddi-ckan-k8s) main branch because we are still discussing some settings with the developer to make the code more efficient. See [here](https://github.com/tum-gis/sddi-ckan-k8s/pull/40).
The clamav function works with the settings we have published ( [sddi-ckan-3.1.0-beta1](https://github.com/tum-gis/sddi-ckan-k8s/releases/tag/sddi-ckan-3.1.0-beta1)] and [ckan-docker v2.1.2](https://github.com/tum-gis/ckan-docker/releases/tag/2.1.2)]

**Pull request merged**
