### PR TITLE
Sddi urban 2.9.9: Changes for OpenShift deploy, further configurability and reduced dependencies

### PR DESCRIPTION
**Pull request by gislab-augsburg**
Proposed Changes:

- make the directories /srv/app/data/ and /srv/app/src/ckan/ckan/public/base/i18n/ writable, in Openshift all files from the image are immutable.
- disable initContainer `init-data`, UID 92 is not working in Openshift and chown is not permitted, so this stops the container startup. We do not need to chown, the PVC ckan is writable and works for us without the init container.

  -> These two are required for a working OpenShift Deploy, they are controlled by the value `ckan: openShift`.

- include a local `production.ini` file included in a local configMap. 
`production.ini` must either be writable during runtime or it must be prefilled with some values (e.g. beaker session secret) for working in OpenShift. Prefilling can be done in a local `production.ini`. Also `ckan.plugins` configuration can be changed here (Setting the value `ckan: plugins` only changes the environment variable, but does not update activated plugins without update_plugins() function being part of `prerun.py`). Also some other configurations like e.g. `scheming.dataset_schemas` cannot be changed by using extra environment variables (extraEnv), but by editing the local `production.ini`.

  -> controlled by the value `ckan: localIni`

- Enable the use of a custom CKAN schema in a local configMap with the extension ckanext-scheming.

  -> controlled by `ckan: schemaConfigMap`

- Create a licenses file included in `ckan-configMap-licenses.yaml` which `ckan: licensesGroupUrl` can use instead of URL to avoid dependency from https://raw.githubusercontent.com/ on container startup

  -> controlled by `ckan: licensesConfigMap` 
  
All Changes are disabled by default so they will not interfere with the standard Kubernetes configuration.

### CODE REVIEW

**Comment by BWibo** [comment]
Hey @gislab-augsburg @klml,

thank you for the contribution and effort you put into this. Your work is greatly appreciated! OpenShift is one of the most popular platforms for managing containerized applications and it would be really cool to support it.

Before I look into your solution in greater detail, I would like to discuss the preconditions we have to _a) support OpenShift_ and _b) additional preconditions for your specific use-case/project_.

I think this would be helpful to find the best solution for all of us.

## Preconditions

### OpenShift support

#### Platform, Helm chart

- Containers cannot as `root`.
- The entire file system (all files and folder) inside a the container should be owned by `root`.
- All files inside the container image are read-only. Thus, all files that need to be writable, have to be mounted e.g. as a volume or `ConfigMap`.

#### Docker image

- To be done

### Project specific

- To be done

Is that correct so far? Is there anything missing? Please comment below, I'll update this comment afterwards.

**Comment by klml** [comment]
LHM has the following requirements for our Openshift

* No privileged system rights (root, sudo) for security reasons
* Ability for rolling deployments (with readiness probe) to ensure high availability of the application.
* Microservices with a maximum of 4 GB RAM and 2 cores CPU in resources to avoid monoliths.
* An automatable CI/CD that can run on OpenShift.
* Be capable of monitoring (health checks, readiness probes)
* custom SecurityContextConstraints are only allowed in exceptional cases, subject to approval by the IT architecture.

**Comment by klml** [comment]
@BWibo All the requirements you mentioned are the same as ours. Requirements such as maximum resources , CICD have already been met anyway

From our point of view, we have covered all requirements with the PR. But the most important thing is that it works for us ;)

**Comment by gislab-augsburg** [comment]
Hey @BWibo
 
thank you very much for your fast reply and great to continue our cooperation here!
In addition to @klml 's comments, I would like to add some thoughts on the preconditions you set up:

> Containers cannot as root. 

-> LHM requirement and OpenShift Standard. There are ways to run OpenShift containers as root, but it's not recommended and a not allowed for LHM OpenShift.

> All files inside the container image are read-only. Thus, all files that need to be writable, have to be mounted e.g. as a volume or ConfigMap.

-> Not all files are read-only, but in our case most files are owned by user ckan, which is not available in LHM OpenShift. We only have an 'arbitrary user' automatically assigned when a pod/container is deployed which cannot write in some files or directories owned by user ckan. Other users could be specified in OpenShift by changing securityContext as I understand it, but this is allowed only in exceptional cases for LHM Openshift, as @klml wrote. So the better way for us is to mount all files that need to be writable as volume or ConfigMap.

> The entire file system (all files and folder) inside a the container should be owned by root.

-> No, I don't think so. 

> **Project specific**

-> We have the following project specific requirements:

- option to include our own local .ini file. This may be a temporary change for (de)activating plugins without building a new image each time and for some settings that did not work with envvars so far.
- option to include our own LHM metadata schema
- remove dependency on raw.githubusercontent.com on container startup. All outbound connections from LHM CAP have to be applied for and being independent is good thing.


@klml Please correct me if I wrote something wrong

**Comment by BWibo** [comment]
Thx for the contribution, but I must say that I'm not a fan of this solution.
It is solves a general problem, that likely affects other people by an implementation, that will only resolve the issue for you. Please checkout #32, where I proposed a more general solution that should work for you and everybody else too.

**Comment by gislab-augsburg** [comment]
I'll close this as our requirements are fully satisfied with #32 
Thanks for that!

**Pull request closed without merging**
