### PR TITLE
Openshift

### PR DESCRIPTION
**Pull request by klml**
Changes required for Openshift
What we need for a working Openshift are (currently) three things:

*  __disable__ initContainer __`init-data`__, UID 92 is not working in Openshift, we need arbitrary UID < 1001
* make the directories `/srv/app/data/` and `/srv/app/src/ckan/ckan/public/base/i18n/` writable, in Openshift all files from the image are immutable.
* get the existing and not empty file `/srv/app/production.ini` also writable.

### CODE REVIEW

**Comment by BWibo** [comment]
Hey there, can you explain the main points we would need to implement to make this chart compatible to Openshift?
From what I get from the commits above it is mainly two features:

- Specify arbitrary *initContainers*
- Specify arbitrary *Volumes*

If this is sufficient, I might have an idea how to resolve this in a lean and professional way.

If we include the [bitnami/common](https://github.com/bitnami/charts/tree/main/bitnami/common) chart, we can use their template renderer to specify both `initContainers` and `extraVolume` in `values.yml`.

Here is an example:

#### `values.yml`

```yml

initContainers:
  - name: init-data
    image: busybox
    command: ["sh", "-c", "chown -Rv 92:92 {{ .Values.persistence.storagePath }}"]
```

#### `deployment.yml`

```yml

# ...
# ...

      initContainers:
        {{- if .Values.primary.initContainers }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
# ...
# ...
```

The same works for volumes.

In values we can have `initContainers` and `extraInitContainer` to overwrite all init containers or just add extra init containers.

**Comment by klml** [comment]
@BWibo thanks for your ideas. I think I can get my requests (I updated the description) resolved with

>    Specify arbitrary initContainers
>    Specify arbitrary Volumes

I will try this, thx ;)

**Comment by BWibo** [comment]
Sure, we're happy for your contributions! Let me know when it's ready for review.

**Comment by BWibo** [comment]
@klml  Any news on this?

**Comment by klml** [comment]
@BWibo sorry for my delay. I've pushed that back a bit. Because I'm actually looking for a solution to store locale configs in addition to production.ini/ckan.ini. But first I have to learn how to do that.

**Comment by klml** [comment]
will be superseeded by sddi-urban-2.9.9

**Comment by BWibo** [comment]
Closed in favor of #31

**Pull request closed without merging**
